g++ all_pairs_dist.cpp -o all_pairs_dist && ./all_pairs_dist ../../data/facebook/0.edges > ../../data/my/dist_mat_0.dat
g++ all_pairs_dist.cpp -o all_pairs_dist && ./all_pairs_dist ../../data/facebook/1.edges > ../../data/my/dist_mat_1.dat
g++ all_pairs_dist.cpp -o all_pairs_dist && ./all_pairs_dist ../../data/facebook/2.edges > ../../data/my/dist_mat_2.dat
g++ all_pairs_dist.cpp -o all_pairs_dist && ./all_pairs_dist ../../data/facebook/3.edges > ../../data/my/dist_mat_3.dat
g++ all_pairs_dist.cpp -o all_pairs_dist && ./all_pairs_dist ../../data/facebook/4.edges > ../../data/my/dist_mat_4.dat
g++ all_pairs_dist.cpp -o all_pairs_dist && ./all_pairs_dist ../../data/facebook/5.edges > ../../data/my/dist_mat_5.dat
g++ all_pairs_dist.cpp -o all_pairs_dist && ./all_pairs_dist ../../data/facebook/6.edges > ../../data/my/dist_mat_6.dat
g++ all_pairs_dist.cpp -o all_pairs_dist && ./all_pairs_dist ../../data/facebook/7.edges > ../../data/my/dist_mat_7.dat
g++ all_pairs_dist.cpp -o all_pairs_dist && ./all_pairs_dist ../../data/facebook/8.edges > ../../data/my/dist_mat_8.dat
